import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'


import { Navbar, MainBanner } from '@/components'


export default function Home() {
	return (
		<>
			<Head>
				<title>Gusto Gastronomia</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="assets/gusto-icon.png" />
			</Head>
			<Navbar />
			<main>
				<MainBanner />
			</main>
		</>
	)
}
