import React, { useRef } from 'react';
import Head from 'next/head'
import {
	Navbar,
	MainBanner,
	About,
	Partner,
	Reference,
	Galery,
	Team,
	Footer,
	Contact,
	Location
} from '@/components'
import AOS from 'aos';

export default function Home() {

	const mainRef = useRef<HTMLElement>(null);
	const aboutRef = useRef<HTMLElement>(null);
	const galeryRef = useRef<HTMLElement>(null);
	const teamRef = useRef<HTMLElement>(null);
	const contactRef = useRef<HTMLElement>(null);

	const refSection = {
		mainRef,
		aboutRef,
		galeryRef,
		teamRef,
		contactRef
	}

	React.useEffect(() => {
		AOS.init()
	}, [])

	return (
		<>
			<Head>
				<title>Gusto Gastronomia</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="assets/gusto-icon.png" />
			</Head>
			<Navbar navRefs={refSection}/>
			<main ref={mainRef}>
				<MainBanner />
			</main>
			<section>
				<Partner />
			</section>
			<section ref={aboutRef}>
				<About />
			</section>
			<section>
				<Reference />
			</section>
			<section ref={galeryRef}>
				<Galery />
			</section>
			<section ref={teamRef}>
				<Team />
			</section>
			<section ref={contactRef}>
				<Contact />
			</section>
			<section>
				<Location />
			</section>
			<footer>
				<Footer />
			</footer>
		</>
	)
}
